import { Card, CollectionType, Recommendation } from '../types/card';

function uuid(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

const now = new Date().toISOString();

function makeCard(overrides: Partial<Card>): Card {
  return {
    id: uuid(),
    collection_type: 'hockey',
    card_name: 'Unknown Card',
    set_name: null,
    year: null,
    card_number: null,
    edition: null,
    rarity: null,
    language: 'English',
    photo_url_front: '',
    photo_url_back: null,
    ai_identification_raw: null,
    ai_confidence_identification: null,
    condition_psa_estimate: null,
    condition_simple: null,
    condition_notes: null,
    is_graded: false,
    grading_company: null,
    graded_score: null,
    grading_cert_number: null,
    estimated_value_usd: null,
    estimated_value_cad: null,
    value_confidence_pct: null,
    value_source_breakdown: null,
    proof_links: null,
    last_valued_at: null,
    ai_recommendation: null,
    ai_recommendation_reasoning: null,
    tags: [],
    notes: null,
    location: null,
    created_at: now,
    updated_at: now,
    ...overrides,
  };
}

export const MOCK_CARDS: Card[] = [
  // ===== HOCKEY =====
  makeCard({
    collection_type: 'hockey',
    card_name: 'Wayne Gretzky Rookie',
    set_name: 'O-Pee-Chee',
    year: 1979,
    card_number: '#18',
    edition: 'Base',
    rarity: 'Rare',
    condition_psa_estimate: 6.0,
    condition_simple: 'Excellent',
    condition_notes: 'Minor corner whitening top-left, slight centering offset 55/45 L-R.',
    estimated_value_usd: 12500.0,
    estimated_value_cad: 17000.0,
    value_confidence_pct: 87,
    last_valued_at: '2026-04-10T12:00:00Z',
    ai_confidence_identification: 0.97,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Iconic rookie card with strong long-term appreciation. Current market is stable. Graded copies in PSA 6 range have risen 15% over the past year. Recommend holding unless immediate liquidity is needed.',
    proof_links: [
      { title: 'Gretzky RC OPC #18 PSA 6 - Sold', price: 12200, date: '2026-03-28', url: 'https://ebay.com/itm/example1' },
      { title: 'Gretzky 1979 OPC Rookie PSA 5.5', price: 10800, date: '2026-03-15', url: 'https://ebay.com/itm/example2' },
      { title: '79 OPC Gretzky RC raw EX', price: 13100, date: '2026-04-02', url: 'https://ebay.com/itm/example3' },
    ],
    tags: ['keeper', 'high-value'],
    location: 'Safe deposit box',
  }),
  makeCard({
    collection_type: 'hockey',
    card_name: 'Connor McDavid Young Guns',
    set_name: 'Upper Deck',
    year: 2015,
    card_number: '#201',
    edition: 'Young Guns',
    rarity: 'Rare',
    condition_psa_estimate: 9.0,
    condition_simple: 'Mint',
    condition_notes: 'Near perfect centering, sharp corners, clean surface.',
    estimated_value_usd: 350.0,
    estimated_value_cad: 476.0,
    value_confidence_pct: 92,
    last_valued_at: '2026-04-08T10:00:00Z',
    ai_confidence_identification: 0.99,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'McDavid continues to dominate the NHL. Young Guns rookies are the most collected modern hockey cards. Strong demand, prices stable with slight upward trend.',
    tags: ['keeper'],
    location: 'Binder 1, Page 1, Slot 1',
  }),
  makeCard({
    collection_type: 'hockey',
    card_name: 'Sidney Crosby Young Guns',
    set_name: 'Upper Deck',
    year: 2005,
    card_number: '#201',
    edition: 'Young Guns',
    rarity: 'Rare',
    condition_psa_estimate: 8.5,
    condition_simple: 'Near Mint',
    estimated_value_usd: 800.0,
    estimated_value_cad: 1088.0,
    value_confidence_pct: 85,
    last_valued_at: '2026-04-05T14:00:00Z',
    ai_confidence_identification: 0.98,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Crosby approaching retirement could spark nostalgia-driven demand. Hold for potential appreciation in next 1-2 years.',
    location: 'Binder 1, Page 2, Slot 1',
  }),
  makeCard({
    collection_type: 'hockey',
    card_name: 'Mario Lemieux Rookie',
    set_name: 'O-Pee-Chee',
    year: 1985,
    card_number: '#9',
    edition: 'Base',
    rarity: 'Rare',
    condition_psa_estimate: 7.0,
    condition_simple: 'Near Mint',
    estimated_value_usd: 275.0,
    estimated_value_cad: 374.0,
    value_confidence_pct: 78,
    last_valued_at: '2026-04-01T09:00:00Z',
    ai_confidence_identification: 0.95,
    ai_recommendation: 'watch',
    ai_recommendation_reasoning: 'Price has been relatively flat. Market for 80s hockey is stable but not growing significantly. Watch for any catalysts.',
    location: 'Binder 1, Page 5, Slot 3',
  }),
  makeCard({
    collection_type: 'hockey',
    card_name: 'Auston Matthews Young Guns',
    set_name: 'Upper Deck',
    year: 2016,
    card_number: '#201',
    edition: 'Young Guns',
    rarity: 'Rare',
    condition_psa_estimate: 9.5,
    condition_simple: 'Mint',
    estimated_value_usd: 220.0,
    estimated_value_cad: 299.0,
    value_confidence_pct: 90,
    last_valued_at: '2026-04-09T16:00:00Z',
    ai_confidence_identification: 0.98,
    ai_recommendation: 'sell_now',
    ai_recommendation_reasoning: 'Matthews market has been declining 10% over 6 months. High raw grade makes this a good sell candidate before further decline.',
    tags: ['for-sale'],
    location: 'Binder 1, Page 3, Slot 2',
  }),

  // ===== MAGIC: THE GATHERING =====
  makeCard({
    collection_type: 'magic',
    card_name: 'Black Lotus',
    set_name: 'Alpha',
    year: 1993,
    card_number: null,
    edition: 'Alpha',
    rarity: 'Rare',
    condition_psa_estimate: 4.0,
    condition_simple: 'Good',
    condition_notes: 'Moderate play wear, slight edge whitening, minor surface scratching. Still clearly identifiable.',
    estimated_value_usd: 85000.0,
    estimated_value_cad: 115600.0,
    value_confidence_pct: 65,
    last_valued_at: '2026-04-06T11:00:00Z',
    ai_confidence_identification: 0.93,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Black Lotus is the most iconic MTG card. Even in played condition, values continue to appreciate. The reserved list guarantees no reprints. Long-term hold.',
    tags: ['keeper', 'high-value', 'reserved-list'],
    location: 'Safe deposit box',
  }),
  makeCard({
    collection_type: 'magic',
    card_name: 'Mox Sapphire',
    set_name: 'Unlimited',
    year: 1993,
    card_number: null,
    edition: 'Unlimited',
    rarity: 'Rare',
    condition_psa_estimate: 6.5,
    condition_simple: 'Excellent',
    estimated_value_usd: 4200.0,
    estimated_value_cad: 5712.0,
    value_confidence_pct: 72,
    last_valued_at: '2026-04-04T08:00:00Z',
    ai_confidence_identification: 0.96,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Reserved list Power 9 card. Steady appreciation. Unlimited edition is more affordable entry point, demand remains strong.',
    tags: ['reserved-list', 'power-9'],
    location: 'Binder 2, Page 1, Slot 1',
  }),
  makeCard({
    collection_type: 'magic',
    card_name: 'Ragavan, Nimble Pilferer',
    set_name: 'Modern Horizons 2',
    year: 2021,
    card_number: '#138',
    edition: 'Regular',
    rarity: 'Mythic Rare',
    condition_psa_estimate: 9.5,
    condition_simple: 'Mint',
    estimated_value_usd: 55.0,
    estimated_value_cad: 74.8,
    value_confidence_pct: 95,
    last_valued_at: '2026-04-10T15:00:00Z',
    ai_confidence_identification: 0.99,
    ai_recommendation: 'sell_now',
    ai_recommendation_reasoning: 'Modern staple but price declining from peak. Multiple reprints possible. Sell while value is still solid.',
    tags: ['modern-staple'],
    location: 'Binder 2, Page 8, Slot 4',
  }),
  makeCard({
    collection_type: 'magic',
    card_name: 'Force of Will',
    set_name: 'Alliances',
    year: 1996,
    card_number: null,
    edition: 'Base',
    rarity: 'Uncommon',
    condition_psa_estimate: 7.5,
    condition_simple: 'Near Mint',
    estimated_value_usd: 95.0,
    estimated_value_cad: 129.2,
    value_confidence_pct: 88,
    last_valued_at: '2026-04-07T13:00:00Z',
    ai_confidence_identification: 0.97,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Legacy and Vintage staple. Original printing holds premium over reprints. Stable value with collector appeal.',
    location: 'Binder 2, Page 3, Slot 2',
  }),
  makeCard({
    collection_type: 'magic',
    card_name: 'The One Ring',
    set_name: 'Lord of the Rings: Tales of Middle-earth',
    year: 2023,
    card_number: '#246',
    edition: 'Regular',
    rarity: 'Mythic Rare',
    condition_psa_estimate: 9.0,
    condition_simple: 'Mint',
    estimated_value_usd: 42.0,
    estimated_value_cad: 57.12,
    value_confidence_pct: 94,
    last_valued_at: '2026-04-11T10:00:00Z',
    ai_confidence_identification: 0.99,
    ai_recommendation: 'watch',
    ai_recommendation_reasoning: 'Banned in Modern, still played in Commander. Price has stabilized after initial hype. Monitor for potential unban or Commander demand shifts.',
    location: 'Binder 2, Page 10, Slot 1',
  }),

  // ===== YU-GI-OH! =====
  makeCard({
    collection_type: 'yugioh',
    card_name: 'Blue-Eyes White Dragon',
    set_name: 'Legend of Blue Eyes White Dragon',
    year: 2002,
    card_number: 'LOB-001',
    edition: '1st Edition',
    rarity: 'Ultra Rare',
    condition_psa_estimate: 7.0,
    condition_simple: 'Near Mint',
    condition_notes: 'Light edge wear on top, corners still sharp. Good centering.',
    estimated_value_usd: 1800.0,
    estimated_value_cad: 2448.0,
    value_confidence_pct: 82,
    last_valued_at: '2026-04-09T09:00:00Z',
    ai_confidence_identification: 0.99,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Iconic Yu-Gi-Oh card. 1st Edition LOB copies have strong collector demand. The 25th anniversary hype has increased interest in vintage YGO. Hold.',
    tags: ['keeper', 'high-value'],
    location: 'Binder 3, Page 1, Slot 1',
  }),
  makeCard({
    collection_type: 'yugioh',
    card_name: 'Dark Magician',
    set_name: 'Legend of Blue Eyes White Dragon',
    year: 2002,
    card_number: 'LOB-005',
    edition: '1st Edition',
    rarity: 'Ultra Rare',
    condition_psa_estimate: 8.0,
    condition_simple: 'Near Mint',
    estimated_value_usd: 950.0,
    estimated_value_cad: 1292.0,
    value_confidence_pct: 80,
    last_valued_at: '2026-04-08T14:00:00Z',
    ai_confidence_identification: 0.98,
    ai_recommendation: 'hold',
    ai_recommendation_reasoning: 'Classic staple with nostalgia value. 1st Edition premium is significant. Market is stable with slight upward trend.',
    location: 'Binder 3, Page 1, Slot 2',
  }),
  makeCard({
    collection_type: 'yugioh',
    card_name: 'Pot of Greed',
    set_name: 'Legend of Blue Eyes White Dragon',
    year: 2002,
    card_number: 'LOB-119',
    edition: '1st Edition',
    rarity: 'Rare',
    condition_psa_estimate: 8.5,
    condition_simple: 'Near Mint',
    estimated_value_usd: 120.0,
    estimated_value_cad: 163.2,
    value_confidence_pct: 91,
    last_valued_at: '2026-04-10T11:00:00Z',
    ai_confidence_identification: 0.99,
    ai_recommendation: 'sell_now',
    ai_recommendation_reasoning: 'Meme value has peaked. Multiple common reprints exist. 1st Ed LOB has premium but trending downward. Good time to sell.',
    tags: ['for-sale'],
    location: 'Binder 3, Page 5, Slot 3',
  }),
  makeCard({
    collection_type: 'yugioh',
    card_name: 'Ash Blossom & Joyous Spring',
    set_name: 'Maximum Crisis',
    year: 2017,
    card_number: 'MACR-EN036',
    edition: '1st Edition',
    rarity: 'Secret Rare',
    condition_psa_estimate: 9.5,
    condition_simple: 'Mint',
    estimated_value_usd: 35.0,
    estimated_value_cad: 47.6,
    value_confidence_pct: 96,
    last_valued_at: '2026-04-11T16:00:00Z',
    ai_confidence_identification: 0.99,
    ai_recommendation: 'sell_now',
    ai_recommendation_reasoning: 'Heavily reprinted staple. Secret Rare 1st Ed still has a premium but multiple tin reprints are pushing prices down. Sell before further reprints erode value.',
    tags: ['for-sale', 'meta-staple'],
    location: 'Binder 3, Page 12, Slot 1',
  }),
  makeCard({
    collection_type: 'yugioh',
    card_name: 'Exodia the Forbidden One',
    set_name: 'Legend of Blue Eyes White Dragon',
    year: 2002,
    card_number: 'LOB-124',
    edition: '1st Edition',
    rarity: 'Ultra Rare',
    condition_psa_estimate: 6.5,
    condition_simple: 'Excellent',
    estimated_value_usd: 650.0,
    estimated_value_cad: 884.0,
    value_confidence_pct: 76,
    last_valued_at: '2026-04-07T10:00:00Z',
    ai_confidence_identification: 0.97,
    ai_recommendation: 'buy_more',
    ai_recommendation_reasoning: 'Complete Exodia sets command significant premiums. This is just the head piece. Consider acquiring the four limb cards to complete the set for maximum value.',
    tags: ['needs-completion'],
    location: 'Binder 3, Page 2, Slot 1',
  }),
];

// Computed summaries from mock data
export function getMockSummary() {
  const cards = MOCK_CARDS;
  const hockey = cards.filter((c) => c.collection_type === 'hockey');
  const magic = cards.filter((c) => c.collection_type === 'magic');
  const yugioh = cards.filter((c) => c.collection_type === 'yugioh');

  const sum = (arr: Card[]) =>
    arr.reduce((s, c) => s + (c.estimated_value_usd ?? 0), 0);
  const avgConf = (arr: Card[]) => {
    const vals = arr.filter((c) => c.value_confidence_pct != null);
    if (vals.length === 0) return 0;
    return Math.round(vals.reduce((s, c) => s + (c.value_confidence_pct ?? 0), 0) / vals.length);
  };
  const countRec = (rec: Recommendation) =>
    cards.filter((c) => c.ai_recommendation === rec).length;

  return {
    totalCards: cards.length,
    totalValueUsd: sum(cards),
    totalValueCad: Math.round(sum(cards) * 1.36 * 100) / 100,
    avgConfidence: avgConf(cards),
    hockey: { cards: hockey.length, value: sum(hockey) },
    magic: { cards: magic.length, value: sum(magic) },
    yugioh: { cards: yugioh.length, value: sum(yugioh) },
    sellNow: countRec('sell_now'),
    hold: countRec('hold'),
    buyMore: countRec('buy_more'),
    watch: countRec('watch'),
    topCards: [...cards]
      .sort((a, b) => (b.estimated_value_usd ?? 0) - (a.estimated_value_usd ?? 0))
      .slice(0, 25),
  };
}
